---
title: "Advent of Code - 2023 - Day 1"
output: html_notebook
---

```{r message=FALSE, warning=FALSE}
# load libraries
library(readr)
library(dplyr)
library(stringr)
```

```{r}
# Create DataFrame
input <- read_csv('input.csv',col_names = 'text_string', col_types = "c")

# Replace number strings to include number
rep_str_digits = c("one"="o1e", "two"="t2o", "three"="t3e", "four"="f4r", "five"="f5e", "six"="s6x", "seven"="s7n", "eight"="e8t", "nine"="n9e")
input$text_string <- str_replace_all(input$text_string, rep_str_digits)

# Remove letters
rep_str_letters = c("a"="", "b"="", "c"="", "d"="", "e"="", "f"="", "g"="", "h"="", "i"="", "j"="", "k"="", "l"="", "m"="", "n"="", "o"="", "p"="", "q"="", "r"="", "s"="", "t"="", "u"="", "v"="", "w"="", "x"="", "y"="", "z"="")
input$text_string <- str_replace_all(input$text_string, rep_str_letters)
head(input)
```

```{r}
# find first and last digits
output <- input
output <- output %>% mutate(first_digit = substr(text_string,1,1))
output <- output %>% transmute(first_digit = first_digit, last_digit = substr(text_string,nchar(text_string),nchar(text_string)))

# bring digits together, convert to number and solve the puzzle
output <- output %>% mutate(cal_value = paste(first_digit, last_digit, sep = "")) %>% 
  mutate(cal_number_value = strtoi(cal_value))
head(output)
solution <- sum(output$cal_number_value)
print(solution)

```